services:
  mongodb:
    image: "mongo:latest"

    volumes:
      - "mongodb-data:/data/db"

    env_file:
      - ./.env

  test-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development

    ports: 
      - "3000:3000"

    volumes:
      - docker-logs:/app/logs
      - /app/node_modules
      - ./:/app

    env_file:
      - ./.env

    depends_on:
      - mongodb

volumes:
  mongodb-data:
  docker-logs:
